<!DOCTYPE html>
<html lang="zh">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>手写promise</title>
</head>

<body>
  <script>
    // https://juejin.im/post/5b2f02cd5188252b937548ab
    class Promise {
      constructor(executor) {
        // 初始化state为等待态
        this.state = 'pending'
        // 成功的值
        this.value = undefined
        // 失败的原因
        this.reason = undefined
        // 成功存放的数组
        this.onResolvedCallbacks = []
        // 失败存放的数组
        this.onRejectedCallbacks = []
        // 成功
        let resolve = value => {
          if (this.state === 'pending') {
            this.state = 'fulfilled'
            this.value = value
            // 执行成功数组里的所有方法
            this.onResolvedCallbacks.forEach(fn => fn())
          }
        }
        // 失败
        let reject = reason => {
          if (this.state === 'pending') {
            this.state = 'rejected'
            this.reason = reason
            // 执行失败数组里的所有方法
            this.onRejectedCallbacks.forEach(fn => fn())
          }
        }
        // 立即执行
        try {
          executor(resolve, rejrct)
        } catch (err) {
          reject(err)
        }

      }
      then(onFulfilled, onRejected) {
        // 声明返回的promise2
        let promise2 = new Promise((resolve, reject) => {
          if (this.state === 'fulfilled') {
            let x = onFulfilled(this.value)
            resolvePromise(promise2, x, resolve, reject)
          }
          if (this.state === 'rejected') {

            let x = onRejected(this.reason)
            resolvePromise(promise2, x, resolve, reject)
          }
          // 当状态state为pending时存起来，解决异步问题
          if (this.state === 'pending') {
            this.onResolvedCallbacks.push(() => {
              onFulfilled(this.value)
            })
            this.onRejectedCallbacks.push(() => {
              onRejected(this.reason)
            })
          }
        })
        // 返回promise，完成链式
        return promise2;

      }


    }

    function resolvePromise(promise2, x, resolve, reject) {
      // 循环引用报错
      if (x === promise2) {
        // reject报错
        return reject(new TypeError('Chaining cycle detected for promise'));
      }
      // 防止多次调用
      let called;
      // x不是null 且x是对象或者函数
      if (x != null && (typeof x === 'object' || typeof x === 'function')) {
        try {
          // A+规定，声明then = x的then方法
          let then = x.then;
          // 如果then是函数，就默认是promise了
          if (typeof then === 'function') {
            // 就让then执行 第一个参数是this   后面是成功的回调 和 失败的回调
            then.call(x, y => {
              // 成功和失败只能调用一个
              if (called) return;
              called = true;
              // resolve的结果依旧是promise 那就继续解析
              resolvePromise(promise2, y, resolve, reject);
            }, err => {
              // 成功和失败只能调用一个
              if (called) return;
              called = true;
              reject(err); // 失败了就失败了
            })
          } else {
            resolve(x); // 直接成功即可
          }
        } catch (e) {
          // 也属于失败
          if (called) return;
          called = true;
          // 取then出错了那就不要在继续执行了
          reject(e);
        }
      } else {
        resolve(x);
      }
    }

    let p = () => {
      return new Promise((resolve, reject) => {
        resolve()
      });
    }
    p().then(res => {
      console.log(1111)
      throw new Error('出错了');
    }).then(res => {
      console.log(3333)
    }).catch(err => {
      console.log(2222)
    })
  </script>
</body>

</html>